package main

/* This file contains the PRU instructions in a Go arrray which are to */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

var pruCode = [...]uint32{
     0x2a000000,
}
